[hints]
[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\\s<>\"\\^`\\[\\]{}|]+"
command.program = "xdg-open"
post_processing = true
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
